Add amount field to donation
hack4impact-mcgill/mu-crm-tool pull request #112
Opened 2021-02-02 03:13 UTC by peterghrong

# Summary

Added amount field to donation
Made column nullable=false
Unfinished migration

	
## Test Plan

Unfinished tests 

## Related Issues

Which issues does this PR resolve/work on?
Closes #100

2021-02-03 00:42 UTC, CurtisMIT requested changes
@peterghrong Besides the minor typo, the migration has not been generated yet. A new version in the migrations folder should be there if a migration has been generated. Pm me if the commands are not working. Nice job!

2021-02-03 00:42 UTC, CurtisMIT commented on backend/tests/test_donation.py
> +class ContactTestCase(unittest.TestCase):
@peterghrong I think you forgot to change the name of the class here.

2021-02-03 04:16 UTC, celinehuang commented
@peterghrong take a look at this - https://flask-migrate.readthedocs.io/en/latest/ should help you with making a migration :)

2021-02-03 04:21 UTC, celinehuang commented
In the future, you can avoid the list of commits by working on your new code with the updated main - either making a branch directly from the version currently on main or rebasing. 

to rebase, it's similar to merging but provides a cleaner commit history (here's an [article](https://www.atlassian.com/git/tutorials/merging-vs-rebasing) if you want to read up about it)

```
$ git checkout main
$ git pull
apply migrations if there are any but you can also do this on your feature branch
$ git checkout featurebranch
$ git fetch
$ git rebase origin/main
$ git push --force
```

2021-02-03 20:58 UTC, peterghrong commented
> In the future, you can avoid the list of commits by working on your new code with the updated main - either making a branch directly from the version currently on main or rebasing.
> 
> to rebase, it's similar to merging but provides a cleaner commit history (here's an [article](https://www.atlassian.com/git/tutorials/merging-vs-rebasing) if you want to read up about it)
> 
> ```
> $ git checkout main
> $ git pull
> apply migrations if there are any but you can also do this on your feature branch
> $ git checkout featurebranch
> $ git fetch
> $ git rebase origin/main
> $ git push --force
> ```
> 
> having a cleaner commit history makes it easier for your reviewers to chance what each commit was doing (sometimes catching bugs etc)

Yes sorry will do in future PRs

2021-02-06 22:58 UTC, CurtisMIT commented
@peterghrong Was wondering whether you could attach a screenshot of the updated table?

2021-02-07 20:27 UTC, peterghrong commented
> @peterghrong Was wondering whether you could attach a screenshot of the updated table?

![Screen Shot 2021-02-07 at 3 25 50 PM](https://user-images.githubusercontent.com/66083521/107158548-ebdb7a00-6958-11eb-9139-571e9bbb96bc.png)

Screenshot taken from pgAdmin with updated amount field in the donation model

2021-02-10 07:57 UTC, CurtisMIT submitted a review, later dismissed
LGTM 💯

2021-02-10 08:04 UTC, CurtisMIT requested changes
@peterghrong Sorry can you show me the data type of the amount column? Sorry should have been more specific.

2021-02-10 15:40 UTC, peterghrong commented
> @peterghrong Sorry can you show me the data type of the amount column? Sorry should have been more specific.

No worries ! I should have thought about that too
![Screen Shot 2021-02-10 at 10 39 48 AM](https://user-images.githubusercontent.com/66083521/107532920-617b5c00-6b8c-11eb-86d1-2be7dcff7414.png)

2021-02-10 22:57 UTC, CurtisMIT approved these changes
LGTM!

2021-02-10 23:01 UTC, merged